In [1]:
import wget
import os.path
import json


import numpy as np
from numpy.linalg import det, inv
from numpy import array
import random

import ase.db
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
from anneling_super_cell import super_cell
from data_import import get_lattice_from_structure, extract_structure

## Model hyperparameters

In [3]:
# Model hyperparameters

up = 99999999
bond =30
model_par = {
    
    'initialTemp': 4, 
    'finalTemp': 0.0002,

    'beta': 10,
    'bounds': [[-bond,bond] for _ in range(4)],

    'nr_neighbours': 1,
    'step_size': 3,
    'gaussian_sd':3,
    
    'known_min': -up,
    "start_point":[1,5,3,2],
    
    "strain_boundary": [[-0.3e-14,0.3e-14],[-0.3e-14,0.3e-14]]#[[-0.3,0.3],[-0.3,0.3]]#[[-0.3e-14,0.3e-14],[-0.3e-14,0.3e-14]]
}



## Tests

In [4]:
# Real lattice tests

# uids for the testing lattices 
uids=["Pd2Se4-12f02221b8c5","C2-a6735a4a3797"]#"C2-a6735a4a3797","WS2-64090c9845f8"]
extract_structure(uids)

structure_path = "STRUCTUREScolection"#/Users/voicutu/Documents/GitHub/vdw_evolve/sandbox/XYZcolection"
uid_1 = "WS2-64090c9845f8"#"VCl2-1ccb0b28392d"
uid_2 = "C2-a6735a4a3797"#"Mn2Se2-a1d595c25fc5"


path1=structure_path+"/"+uid_1+".json"
path2=structure_path+"/"+uid_2+".json"

# lattices
latice1 = get_lattice_from_structure(path1)
latice2 = get_lattice_from_structure(path2)


cel1 = np.array([[latice1[0][0], latice1[1][0]],
        [latice1[0][1], latice1[1][1]]])

cel2 = np.array([[latice2[0][0], latice2[1][0]],
        [latice2[0][1], latice2[1][1]]])

tA, tB, t_cel2_no_strain, diagonal_strain, strain = super_cell(cel1,cel2, 10, model_par)

s_cell= np.dot(tA,cel1)
zero = np.dot(tA,cel1)-np.dot(np.dot(strain,tB),cel2)

print("\ncel1\n",cel1)
print("cel2\n",cel2)
print("\n=====================\n")
print("\n _____\n tA:\n",tA)
print("det:",det(tA))
print("\n _____\n tB:\n",tB)
print("\n _____\n zero:\n",np.dot(tA,cel1)-np.dot(tB,cel2))
print("\n=====================\n")
print("\n _____\n t_cel2_no_strain:\n",t_cel2_no_strain)
print("\n _____\n Strain diagonal :\n",diagonal_strain)
print("\n=====================\n")
print("\n _____\n Strain:\n", strain)
print("\n _____\n tB_strained:\n", np.dot(strain,tB))
print("\n _____\n Zero:\n", zero)
print("\n=====================\n")
print("\n _____\n Super cell:\n",s_cell)
print("det:",det(s_cell))

https://cmrdb.fysik.dtu.dk/c2db/row/Pd2Se4-12f02221b8c5/data/structure.json
file:  STRUCTUREScolection/Pd2Se4-12f02221b8c5.json found
https://cmrdb.fysik.dtu.dk/c2db/row/C2-a6735a4a3797/data/structure.json
file:  STRUCTUREScolection/C2-a6735a4a3797.json found
temp:4|epoch:0|change:-99504167094087.6|value:5429981067291.367
temp:4|epoch:5|change:2750009567322.8887|value:5429981067291.367
temp:0.0975609756097561|epoch:0|change:37025022721737.54|value:24966799092.647747
temp:0.0975609756097561|epoch:5|change:236967960012553.97|value:24966799092.647747
temp:0.04938271604938272|epoch:0|change:606682654930.0637|value:24966799092.647747
temp:0.04938271604938272|epoch:5|change:52297848519763.71|value:24966799092.647747
temp:0.03305785123966942|epoch:0|change:442724211891.0689|value:24966799092.647747
temp:0.03305785123966942|epoch:5|change:35261178089565.195|value:24966799092.647747
temp:0.02484472049689441|epoch:0|change:7940312123302.52|value:24966799092.647747
temp:0.02484472049689441|epoch:

temp:0.0020822488287350347|epoch:5|change:3355712251125.7227|value:10334425141.412031
temp:0.0020397756246812856|epoch:0|change:71045500899388.2|value:10334425141.412031
temp:0.0020397756246812856|epoch:5|change:26608914357832.38|value:10334425141.412031
temp:0.0019990004997501253|epoch:0|change:45286301338038.336|value:10334425141.412031
temp:0.0019990004997501253|epoch:5|change:199416679389419.3|value:10334425141.412031
temp:0.0019598236158745717|epoch:0|change:56446363425813.51|value:10334425141.412031
temp:0.0019598236158745717|epoch:5|change:63397962674207.55|value:10334425141.412031
temp:0.0019221528111484868|epoch:0|change:46952923874028.555|value:10334425141.412031
temp:0.0019221528111484868|epoch:5|change:41751183620414.21|value:10334425141.412031
temp:0.0018859028760018863|epoch:0|change:25013190261895.875|value:10334425141.412031
temp:0.0018859028760018863|epoch:5|change:12669295657220.26|value:10334425141.412031
temp:0.0018509949097639986|epoch:0|change:35373056746461.125|v

temp:0.0010201479214486096|epoch:0|change:249702262136430.72|value:10334425141.412031
temp:0.0010201479214486096|epoch:5|change:9099148001064.232|value:10334425141.412031
temp:0.0010098459984852306|epoch:0|change:461268994237.8813|value:10334425141.412031
temp:0.0010098459984852306|epoch:5|change:276175378997643.34|value:10334425141.412031
temp:0.0009997500624843783|epoch:0|change:14282912347709.113|value:10334425141.412031
temp:0.0009997500624843783|epoch:5|change:112640357644841.14|value:10334425141.412031
temp:0.0009898539965355103|epoch:0|change:33068447733194.777|value:10334425141.412031
temp:0.0009898539965355103|epoch:5|change:19628490600586.996|value:10334425141.412031
temp:0.0009801519235481493|epoch:0|change:58149831822062.65|value:10334425141.412031
temp:0.0009801519235481493|epoch:5|change:62007679906859.18|value:10334425141.412031
temp:0.0009706381946129574|epoch:0|change:88936875884845.38|value:10334425141.412031
temp:0.0009706381946129574|epoch:5|change:60993353554558.52

temp:0.000671028350947827|epoch:0|change:4144551199910.5757|value:6183988385.01865
temp:0.000671028350947827|epoch:5|change:99214960717471.56|value:6183988385.01865
temp:0.0006665555740709876|epoch:0|change:52600841872558.09|value:6183988385.01865
temp:0.0006665555740709876|epoch:5|change:3382793243593.794|value:6183988385.01865
temp:0.0006621420294653197|epoch:0|change:34310875665868.08|value:6183988385.01865
temp:0.0006621420294653197|epoch:5|change:60782397378049.414|value:6183988385.01865
temp:0.0006577865482650873|epoch:0|change:1978760877816.1218|value:6183988385.01865
temp:0.0006577865482650873|epoch:5|change:79185595176552.56|value:6183988385.01865
temp:0.0006534879921581434|epoch:0|change:26341845570691.414|value:6183988385.01865
temp:0.0006534879921581434|epoch:5|change:32450346834074.74|value:6183988385.01865
temp:0.0006492452523940912|epoch:0|change:54884863923063.08|value:6183988385.01865
temp:0.0006492452523940912|epoch:5|change:75135170516394.16|value:6183988385.01865
te

temp:0.0005049867440979674|epoch:5|change:18499159715630.492|value:5119956182.712087
temp:0.0005024494410249969|epoch:0|change:92744502602832.11|value:5119956182.712087
temp:0.0005024494410249969|epoch:5|change:33970659994273.477|value:5119956182.712087
temp:0.0004999375078115236|epoch:0|change:120571277776175.16|value:5119956182.712087
temp:0.0004999375078115236|epoch:5|change:84909880154402.39|value:5119956182.712087
temp:0.0004974505658500187|epoch:0|change:22770380018747.68|value:5119956182.712087
temp:0.0004974505658500187|epoch:5|change:49693514384304.17|value:5119956182.712087
temp:0.0004949882440292043|epoch:0|change:1073400350873.4504|value:5119956182.712087
temp:0.0004949882440292043|epoch:5|change:70694083645995.8|value:5119956182.712087
temp:0.0004925501785494397|epoch:0|change:37683108806913.88|value:5119956182.712087
temp:0.0004925501785494397|epoch:5|change:111900652828732.77|value:5119956182.712087
temp:0.0004901360127435363|epoch:0|change:78069390410813.48|value:511995

temp:0.0004015661078205002|epoch:0|change:7070442818368.277|value:5119956182.712087
temp:0.0004015661078205002|epoch:5|change:157588779601146.78|value:5119956182.712087
temp:0.00039996000399960033|epoch:0|change:14007686347078.11|value:5119956182.712087
temp:0.00039996000399960033|epoch:5|change:5190018857407.349|value:5119956182.712087
temp:0.0003983666965441692|epoch:0|change:8293152396856.711|value:5119956182.712087
temp:0.0003983666965441692|epoch:5|change:228932115104416.84|value:5119956182.712087
temp:0.0003967860331316341|epoch:0|change:39168427190049.6|value:5119956182.712087
temp:0.0003967860331316341|epoch:5|change:79436879604112.73|value:5119956182.712087
temp:0.0003952178638474463|epoch:0|change:96684375413200.5|value:5119956182.712087
temp:0.0003952178638474463|epoch:5|change:11292557343499.484|value:5119956182.712087
temp:0.00039366204113768367|epoch:0|change:23400458245233.027|value:5119956182.712087
temp:0.00039366204113768367|epoch:5|change:1175283088875.229|value:5119

temp:0.0003344201989800189|epoch:0|change:120047287801861.8|value:5119956182.712087
temp:0.0003344201989800189|epoch:5|change:35526830420685.93|value:5119956182.712087
temp:0.000333305557870178|epoch:0|change:30004287747102.332|value:5119956182.712087
temp:0.000333305557870178|epoch:5|change:25100431397769.71|value:5119956182.712087
temp:0.0003321983223984724|epoch:0|change:20956328723343.027|value:5119956182.712087
temp:0.0003321983223984724|epoch:5|change:8218815263697.114|value:5119956182.712087
temp:0.0003310984190050497|epoch:0|change:4086003840753.7095|value:5119956182.712087
temp:0.0003310984190050497|epoch:5|change:42630643622773.89|value:5119956182.712087
temp:0.00033000577510106473|epoch:0|change:30944315687840.344|value:5119956182.712087
temp:0.00033000577510106473|epoch:5|change:23202517299569.277|value:5119956182.712087
temp:0.00032892031905270994|epoch:0|change:2893945184503.2637|value:5119956182.712087
temp:0.00032892031905270994|epoch:5|change:2222762937184.663|value:51

temp:0.0002873356799080528|epoch:5|change:1613860041812.0168|value:5119956182.712087
temp:0.000286512427476542|epoch:0|change:12922729752623.1|value:5119956182.712087
temp:0.000286512427476542|epoch:5|change:34218713695182.875|value:5119956182.712087
temp:0.0002856938790086424|epoch:0|change:92531300367847.05|value:5119956182.712087
temp:0.0002856938790086424|epoch:5|change:23460375859055.734|value:5119956182.712087
temp:0.00028487999430240027|epoch:0|change:46682716953649.05|value:5119956182.712087
temp:0.00028487999430240027|epoch:5|change:1136726974190165.0|value:5119956182.712087
temp:0.0002840707336126697|epoch:0|change:34716753672943.8|value:5119956182.712087
temp:0.0002840707336126697|epoch:5|change:18111536278194.156|value:5119956182.712087
temp:0.00028326605764464287|epoch:0|change:106760638052888.97|value:5119956182.712087
temp:0.00028326605764464287|epoch:5|change:25071546261401.96|value:5119956182.712087
temp:0.00028246592754748974|epoch:0|change:1649147142484.6821|value:51

temp:0.0002506108639809535|epoch:0|change:7542594168819.071|value:633739219.5369387
temp:0.0002506108639809535|epoch:5|change:46785161497096.016|value:633739219.5369387
temp:0.0002499843759765014|epoch:0|change:5954502278720.472|value:633739219.5369387
temp:0.0002499843759765014|epoch:5|change:39816732847245.61|value:633739219.5369387
temp:0.00024936101240571033|epoch:0|change:181438863706047.2|value:633739219.5369387
temp:0.00024936101240571033|epoch:5|change:33211057608203.527|value:633739219.5369387
temp:0.0002487407499533611|epoch:0|change:6142753287377.431|value:633739219.5369387
temp:0.0002487407499533611|epoch:5|change:2047171768105.298|value:633739219.5369387
temp:0.0002481235655356367|epoch:0|change:33373428750370.586|value:633739219.5369387
temp:0.0002481235655356367|epoch:5|change:47931560771993.33|value:633739219.5369387
temp:0.0002475094362972588|epoch:0|change:10924647992670.992|value:633739219.5369387
temp:0.0002475094362972588|epoch:5|change:3136965752797.1904|value:633

temp:0.00022270474917877623|epoch:5|change:64945896142776.12|value:633649319.9037153
temp:0.0002222098772290428|epoch:0|change:141306526421320.97|value:633649319.9037153
temp:0.0002222098772290428|epoch:5|change:1020503337770.8239|value:633649319.9037153
temp:0.0002217171997117676|epoch:0|change:303371611092898.6|value:633649319.9037153
temp:0.0002217171997117676|epoch:5|change:22771883998649.195|value:633649319.9037153
temp:0.00022122670206293897|epoch:0|change:116959873651106.52|value:633649319.9037153
temp:0.00022122670206293897|epoch:5|change:41433564716223.45|value:633649319.9037153
temp:0.00022073836984713862|epoch:0|change:14495234516724.145|value:633649319.9037153
temp:0.00022073836984713862|epoch:5|change:7367713086746.961|value:633649319.9037153
temp:0.00022025218875612574|epoch:0|change:29723259265236.426|value:633649319.9037153
temp:0.00022025218875612574|epoch:5|change:5650022391728.991|value:633649319.9037153
temp:0.00021976814460743913|epoch:0|change:5458706524586.152|va

In [ ]:
cel1
 [[ 3.18594595 -1.59297297]
 [ 0.          2.75911013]]
cel2
 [[ 2.46723126e+00 -1.23361563e+00]
 [-1.75506857e-20  2.13668495e+00]]

=====================


 _____
 tA:
 [[12  6]
 [15  6]]
det: -17.99999999999999

 _____
 tB:
 [[15.49564972  7.74782486]
 [19.36956215  7.74782486]]

 _____
 zero:
 [[ 0.00000000e+00 -3.55271368e-15]
 [-7.10542736e-15  0.00000000e+00]]

=====================


 _____
 t_cel2_no_strain:
 [[15.94514737  7.50359876]
 [19.69694675  7.50359876]]

 _____
 Strain diagonal :
 [[1.28864667 0.        ]
 [0.         1.28946272]]

=====================


 _____
 Strain:
 [[ 1.29068483 -0.25813697]
 [ 0.25813697  0.7744109 ]]

 _____
 tB_strained:
 [[15.  8.]
 [19.  8.]]

 _____
 Zero:
 [[ 1.22288249 -1.15026007]
 [ 0.9117953  -0.99471647]]

=====================


 _____
 Super cell:
 [[38.2313514  -2.56101493]
 [47.78918924 -7.33993386]]
det: -158.22676323629145

In [ ]:
# custom 

a1 = [1,0]; a2=[0,1]
A  = np.transpose([a1,a2])

theta =  np.pi/4
R = [ [ np.cos(theta), -np.sin(theta)], [ np.sin(theta),  np.cos(theta)] ]

b1 = np.sqrt(2)*np.dot(R,a1);  b2 = a2#np.sqrt(2)*np.dot(R,a2) #a2
#b1 = [np.sqrt(2),0]; b2=[0,np.sqrt(2)]
B  = np.transpose([b1,b2])


cel1 = np.array(A)
cel2 = np.array(B)

tA, tB, t_cel2_no_strain, diagonal_strain, strain = super_cell(cel1, cel2, 10, model_par)

zero = np.dot(tA,cel1)-np.dot(np.dot(strain,tB),cel2)
s_cell= np.dot(tA,cel1)


print("\ncel1\n",cel1)
print("cel2\n",cel2)
print("\n=====================\n")
print("\n _____\n tA:\n",tA)
print("det:",det(tA))
print("\n _____\n tB:\n",tB)
print("\n _____\n zero:\n",np.dot(tA,cel1)-np.dot(tB,cel2))
print("\n=====================\n")
print("\n _____\n t_cel2_no_strain:\n",t_cel2_no_strain)
print("\n _____\n Strain diagonal :\n",diagonal_strain)
print("\n=====================\n")
print("\n _____\n Strain:\n", strain)
print("\n _____\n tB_strained:\n", np.dot(strain,tB))
print("\n _____\n Zero:\n", zero)
print("\n=====================\n")
print("\n _____\n Super cell:\n",s_cell)
print("det:",det(s_cell))

temp:4|epoch:0|change:39477.884268997914|value:32522.850570895498
temp:4|epoch:5|change:117897.9646017648|value:-70075.97376424226
temp:0.0975609756097561|epoch:0|change:-71092.39358400079|value:-141168.36734824305
temp:0.0975609756097561|epoch:5|change:45381695.15570335|value:-141168.36734824305
temp:0.04938271604938272|epoch:0|change:85164979.65546471|value:-49982598.50000002
temp:0.04938271604938272|epoch:5|change:48795750.42818431|value:-49982598.50000002
temp:0.03305785123966942|epoch:0|change:49851030.132651776|value:-49982598.50000002
temp:0.03305785123966942|epoch:5|change:48778950.4281843|value:-49982598.50000002
temp:0.02484472049689441|epoch:0|change:52099599.54221355|value:-49982598.50000002
temp:0.02484472049689441|epoch:5|change:53750796.82031083|value:-49982598.50000002
temp:0.01990049751243781|epoch:0|change:50174774.5064125|value:-49982598.50000002
temp:0.01990049751243781|epoch:5|change:50075697.64829799|value:-49982598.50000002
temp:0.016597510373443983|epoch:0|chang

temp:0.0018509949097639986|epoch:0|change:52098999.54221353|value:-49999598.5
temp:0.0018509949097639986|epoch:5|change:51892169.14355056|value:-49999598.5
temp:0.0018173557473875517|epoch:0|change:50470604.67208744|value:-49999598.5
temp:0.0018173557473875517|epoch:5|change:50166374.50641248|value:-49999598.5
temp:0.0017849174475680506|epoch:0|change:59851213.332030736|value:-49999598.5
temp:0.0017849174475680506|epoch:5|change:49971070.547468945|value:-49999598.5
temp:0.0017536168347216138|epoch:0|change:53761796.82031081|value:-49999598.5
temp:0.0017536168347216138|epoch:5|change:49995159.25617378|value:-49999598.5
temp:0.0017233950883239987|epoch:0|change:50042220.49083752|value:-49999598.5
temp:0.0017233950883239987|epoch:5|change:50288225.15739239|value:-49999598.5
temp:0.0016941973739940707|epoch:0|change:50543594.334085375|value:-49999598.5
temp:0.0016941973739940707|epoch:5|change:49927122.52623576|value:-49999598.5
temp:0.0016659725114535613|epoch:0|change:1000000150005997.4|

temp:0.0009257116408238829|epoch:0|change:48783950.428184286|value:-49999598.5
temp:0.0009257116408238829|epoch:5|change:53124935.36376212|value:-49999598.5
temp:0.0009172208209126342|epoch:0|change:50036568.84025463|value:-49999598.5
temp:0.0009172208209126342|epoch:5|change:49928122.52623576|value:-49999598.5
temp:0.000908884344467166|epoch:0|change:52330555.27502267|value:-49999598.5
temp:0.000908884344467166|epoch:5|change:49614318.50802529|value:-49999598.5
temp:0.0009006980409817604|epoch:0|change:50415718.50225792|value:-49999598.5
temp:0.0009006980409817604|epoch:5|change:51513307.86196094|value:-49999598.5
temp:0.0008926578888640924|epoch:0|change:1000000149999997.4|value:-49999598.5
temp:0.0008926578888640924|epoch:5|change:1000000150028797.4|value:-49999598.5
temp:0.0008847600088475996|epoch:0|change:50091545.21413524|value:-49999598.5
temp:0.0008847600088475996|epoch:5|change:50289025.15739239|value:-49999598.5
temp:0.0008770006577504927|epoch:0|change:49929522.52623576|val

temp:0.0006210215804999219|epoch:5|change:50407718.50225792|value:-49999598.5
temp:0.0006171887054466898|epoch:0|change:52102799.54221353|value:-49999598.5
temp:0.0006171887054466898|epoch:5|change:49984159.41237872|value:-49999598.5
temp:0.0006134028523232628|epoch:0|change:50825476.04447464|value:-49999598.5
temp:0.0006134028523232628|epoch:5|change:67880568.89819235|value:-49999598.5
temp:0.0006096631611034899|epoch:0|change:49938322.52623576|value:-49999598.5
temp:0.0006096631611034899|epoch:5|change:49622718.50802529|value:-49999598.5
temp:0.0006059687926071803|epoch:0|change:50044425.208685294|value:-49999598.5
temp:0.0006059687926071803|epoch:5|change:50206084.31586986|value:-49999598.5
temp:0.0006023189278723081|epoch:0|change:1000000150004597.4|value:-49999598.5
temp:0.0006023189278723081|epoch:5|change:51694963.96338957|value:-49999598.5
temp:0.0005987127675497677|epoch:0|change:60579293.02702434|value:-49999598.5
temp:0.0005987127675497677|epoch:5|change:44121454.86764706|va

temp:0.00046506220206952694|epoch:5|change:50938490.21991788|value:-49999598.5
temp:0.00046290938548779095|epoch:0|change:50012568.84025463|value:-49999598.5
temp:0.00046290938548779095|epoch:5|change:50143431.17262629|value:-49999598.5
temp:0.0004607764082478979|epoch:0|change:1000000150014397.4|value:-49999598.5
temp:0.0004607764082478979|epoch:5|change:48810350.42818428|value:-49999598.5
temp:0.000458662997362688|epoch:0|change:50718457.11486932|value:-49999598.5
temp:0.000458662997362688|epoch:5|change:51349148.66944229|value:-49999598.5
temp:0.0004565688848304991|epoch:0|change:50055420.49083752|value:-49999598.5
temp:0.0004565688848304991|epoch:5|change:49615918.50802529|value:-49999598.5
temp:0.0004544938075218728|epoch:0|change:50027425.208685294|value:-49999598.5
temp:0.0004544938075218728|epoch:5|change:54115150.11397357|value:-49999598.5
temp:0.00045243750706933637|epoch:0|change:60572893.02702434|value:-49999598.5
temp:0.00045243750706933637|epoch:5|change:50221284.31586986

temp:0.00037171266610909817|epoch:0|change:13600.0|value:-49999598.5
temp:0.00037171266610909817|epoch:5|change:49950522.52623576|value:-49999598.5
temp:0.0003703360799925938|epoch:0|change:50052820.49083752|value:-49999598.5
temp:0.0003703360799925938|epoch:5|change:8999.999999955297|value:-49999598.5
temp:0.0003689696522461033|epoch:0|change:49927122.52623576|value:-49999598.5
temp:0.0003689696522461033|epoch:5|change:51702563.96338957|value:-49999598.5
temp:0.0003676132708390778|epoch:0|change:50167174.50641248|value:-49999598.5
temp:0.0003676132708390778|epoch:5|change:49627118.50802529|value:-49999598.5
temp:0.00036626682538229156|epoch:0|change:52577360.438140646|value:-49999598.5
temp:0.00036626682538229156|epoch:5|change:50042521.350570895|value:-49999598.5
temp:0.00036493020709789305|epoch:0|change:51515707.86196094|value:-49999598.5
temp:0.00036493020709789305|epoch:5|change:50112774.91348108|value:-49999598.5
temp:0.0003636033087901105|epoch:0|change:50243860.62048307|value: