In [1]:
import wget
import os.path
import json


import numpy as np
from numpy.linalg import det, inv
from numpy import array
import random

import ase.db
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
from anneling_super_cell import super_cell
from data_import import get_lattice_from_structure, extract_structure

## Model hyperparameters

In [3]:
# Model hyperparameters

up = 99999999
bond =30
model_par = {
    
    'initialTemp': 4, 
    'finalTemp': 0.0002,

    'beta': 10,
    'bounds': [[-bond,bond] for _ in range(4)],

    'nr_neighbours': 1,
    'step_size': 3,
    'gaussian_sd':3,
    
    'known_min': -up,
    "start_point":[1,5,3,2],
    
    "strain_boundary": [[-0.3,0.3],[-0.3,0.3]]#[[-0.3e-14,0.3e-14],[-0.3e-14,0.3e-14]]
}



## Tests

In [4]:
# Real lattice tests

# uids for the testing lattices 
uids=["Pd2Se4-12f02221b8c5","C2-a6735a4a3797"]#"C2-a6735a4a3797","WS2-64090c9845f8"]
extract_structure(uids)

structure_path = "STRUCTUREScolection"#/Users/voicutu/Documents/GitHub/vdw_evolve/sandbox/XYZcolection"
uid_1 = uids[0]#"WS2-64090c9845f8"#"VCl2-1ccb0b28392d"
uid_2 = uids[1]#"C2-a6735a4a3797"#"Mn2Se2-a1d595c25fc5"


path1=structure_path+"/"+uid_1+".json"
path2=structure_path+"/"+uid_2+".json"

# lattices
latice1 = get_lattice_from_structure(path1)
latice2 = get_lattice_from_structure(path2)


cel1 = np.array([[latice1[0][0], latice1[1][0]],
        [latice1[0][1], latice1[1][1]]])

cel2 = np.array([[latice2[0][0], latice2[1][0]],
        [latice2[0][1], latice2[1][1]]])

tA, tB, t_cel2_no_strain, diagonal_strain, strain = super_cell(cel1,cel2, 10, model_par)

s_cell= np.dot(tA,cel1)
zero = np.dot(tA,cel1)-np.dot(np.dot(strain,tB),cel2)

print("\ncel1\n",cel1)
print("cel2\n",cel2)
print("\n=====================\n")
print("\n _____\n tA:\n",tA)
print("det:",det(tA))
print("\n _____\n tB:\n",tB)
print("\n _____\n zero:\n",np.dot(tA,cel1)-np.dot(tB,cel2))
print("\n=====================\n")
print("\n _____\n t_cel2_no_strain:\n",t_cel2_no_strain)
print("\n _____\n Strain diagonal :\n",diagonal_strain)
print("\n=====================\n")
print("\n _____\n Strain:\n", strain)
print("\n _____\n tB_strained:\n", np.dot(strain,tB))
print("\n _____\n Zero:\n", zero)
print("\n=====================\n")
print("\n _____\n Super cell:\n",s_cell)
print("det:",det(s_cell))

https://cmrdb.fysik.dtu.dk/c2db/row/Pd2Se4-12f02221b8c5/data/structure.json
file:  STRUCTUREScolection/Pd2Se4-12f02221b8c5.json found
https://cmrdb.fysik.dtu.dk/c2db/row/C2-a6735a4a3797/data/structure.json
file:  STRUCTUREScolection/C2-a6735a4a3797.json found
temp:4|epoch:0|change:61439234444347.38|value:3205339365698.348
temp:4|epoch:5|change:2131345922023.9302|value:149132650750.90866
temp:0.0975609756097561|epoch:0|change:251697936659791.16|value:149132650750.90866
temp:0.0975609756097561|epoch:5|change:681298186114218.9|value:149132650750.90866
temp:0.04938271604938272|epoch:0|change:226682373449324.94|value:149132650750.90866
temp:0.04938271604938272|epoch:5|change:2255538511188.513|value:149132650750.90866
temp:0.03305785123966942|epoch:0|change:7775751935794.45|value:149132650750.90866
temp:0.03305785123966942|epoch:5|change:6328613870.981354|value:149132650750.90866
temp:0.02484472049689441|epoch:0|change:34849860053151.055|value:149132650750.90866
temp:0.02484472049689441|epoc

temp:0.0020397756246812856|epoch:0|change:492012654194.162|value:1453547860.9197526
temp:0.0020397756246812856|epoch:5|change:1669303396035.2756|value:1453547860.9197526
temp:0.0019990004997501253|epoch:0|change:163250325227702.56|value:1453547860.9197526
temp:0.0019990004997501253|epoch:5|change:46834781908643.64|value:1453547860.9197526
temp:0.0019598236158745717|epoch:0|change:12536810378103.168|value:1453547860.9197526
temp:0.0019598236158745717|epoch:5|change:36174544655470.89|value:1453547860.9197526
temp:0.0019221528111484868|epoch:0|change:41531935664820.734|value:1453547860.9197526
temp:0.0019221528111484868|epoch:5|change:2315088250201.059|value:1453547860.9197526
temp:0.0018859028760018863|epoch:0|change:66886701981602.21|value:1453547860.9197526
temp:0.0018859028760018863|epoch:5|change:45608338422439.37|value:1453547860.9197526
temp:0.0018509949097639986|epoch:0|change:72690764190.8178|value:1453547860.9197526
temp:0.0018509949097639986|epoch:5|change:11500743574048.19|val

temp:0.0010201479214486096|epoch:5|change:6684609206977.578|value:446894738.87545466
temp:0.0010098459984852306|epoch:0|change:1428449612768.07|value:446894738.87545466
temp:0.0010098459984852306|epoch:5|change:1627605147901.6077|value:446894738.87545466
temp:0.0009997500624843783|epoch:0|change:318704039031.8516|value:446894738.87545466
temp:0.0009997500624843783|epoch:5|change:1427487763773.9412|value:446894738.87545466
temp:0.0009898539965355103|epoch:0|change:1000002186007510.0|value:446894738.87545466
temp:0.0009898539965355103|epoch:5|change:1858941942504.6982|value:446894738.87545466
temp:0.0009801519235481493|epoch:0|change:122168343279685.39|value:446894738.87545466
temp:0.0009801519235481493|epoch:5|change:2699998633577.9497|value:446894738.87545466
temp:0.0009706381946129574|epoch:0|change:115361817497.7701|value:446894738.87545466
temp:0.0009706381946129574|epoch:5|change:10603739220978.043|value:446894738.87545466
temp:0.0009613073780341257|epoch:0|change:109824922438868.8

temp:0.0006755615605472042|epoch:5|change:28476079115122.453|value:22477921.88208431
temp:0.000671028350947827|epoch:0|change:109955042963905.28|value:22477921.88208431
temp:0.000671028350947827|epoch:5|change:2271359587202.258|value:22477921.88208431
temp:0.0006665555740709876|epoch:0|change:2712899854541.587|value:22477921.88208431
temp:0.0006665555740709876|epoch:5|change:10448970783840.908|value:22477921.88208431
temp:0.0006621420294653197|epoch:0|change:474267020629.40686|value:22477921.88208431
temp:0.0006621420294653197|epoch:5|change:4973056753882.641|value:22477921.88208431
temp:0.0006577865482650873|epoch:0|change:151491401.81314117|value:22477921.88208431
temp:0.0006577865482650873|epoch:5|change:63537399148986.51|value:22477921.88208431
temp:0.0006534879921581434|epoch:0|change:3776686150731.57|value:22477921.88208431
temp:0.0006534879921581434|epoch:5|change:3830176430961.9604|value:22477921.88208431
temp:0.0006492452523940912|epoch:0|change:11419826873299.268|value:224779

temp:0.0005024494410249969|epoch:0|change:4376471781209.395|value:22477921.88208431
temp:0.0005024494410249969|epoch:5|change:6066394870552.518|value:22477921.88208431
temp:0.0004999375078115236|epoch:0|change:2750782358303.7114|value:22477921.88208431
temp:0.0004999375078115236|epoch:5|change:5963241858.459232|value:22477921.88208431
temp:0.0004974505658500187|epoch:0|change:17275720397094.004|value:22477921.88208431
temp:0.0004974505658500187|epoch:5|change:219958559419.41632|value:22477921.88208431
temp:0.0004949882440292043|epoch:0|change:9191193496898.686|value:22477921.88208431
temp:0.0004949882440292043|epoch:5|change:1782452797.4535737|value:22477921.88208431
temp:0.0004925501785494397|epoch:0|change:14894477745334.469|value:22477921.88208431
temp:0.0004925501785494397|epoch:5|change:36032767716180.27|value:22477921.88208431
temp:0.0004901360127435363|epoch:0|change:196742869512.36395|value:22477921.88208431
temp:0.0004901360127435363|epoch:5|change:114067877059954.45|value:224

temp:0.00040318516278600974|epoch:0|change:6752872155995.068|value:21727990.83088348
temp:0.00040318516278600974|epoch:5|change:82917897116775.94|value:21727990.83088348
temp:0.0004015661078205002|epoch:0|change:3506246326745.883|value:21727990.83088348
temp:0.0004015661078205002|epoch:5|change:2023745926690.803|value:21727990.83088348
temp:0.00039996000399960033|epoch:0|change:5020835632543.265|value:21727990.83088348
temp:0.00039996000399960033|epoch:5|change:2241867975233.7827|value:21727990.83088348
temp:0.0003983666965441692|epoch:0|change:20088956280085.92|value:21727990.83088348
temp:0.0003983666965441692|epoch:5|change:468041189262.7641|value:21727990.83088348
temp:0.0003967860331316341|epoch:0|change:10508768693088.807|value:21727990.83088348
temp:0.0003967860331316341|epoch:5|change:305946814811802.1|value:21727990.83088348
temp:0.0003952178638474463|epoch:0|change:4833536606063.332|value:21727990.83088348
temp:0.0003952178638474463|epoch:5|change:245663327034.47144|value:217

temp:0.00033554232027514525|epoch:0|change:275952493242.6263|value:21727990.83088348
temp:0.00033554232027514525|epoch:5|change:173909835813183.7|value:21727990.83088348
temp:0.0003344201989800189|epoch:0|change:11545007931998.037|value:21727990.83088348
temp:0.0003344201989800189|epoch:5|change:2549800443716.1733|value:21727990.83088348
temp:0.000333305557870178|epoch:0|change:339051284288.3187|value:21727990.83088348
temp:0.000333305557870178|epoch:5|change:1430027673763.8313|value:21727990.83088348
temp:0.0003321983223984724|epoch:0|change:67858569332364.234|value:21727990.83088348
temp:0.0003321983223984724|epoch:5|change:183410772515.35748|value:21727990.83088348
temp:0.0003310984190050497|epoch:0|change:4643157593370.114|value:21727990.83088348
temp:0.0003310984190050497|epoch:5|change:70076085347390.555|value:21727990.83088348
temp:0.00033000577510106473|epoch:0|change:970448583017.598|value:21727990.83088348
temp:0.00033000577510106473|epoch:5|change:1000000078391668.6|value:21

temp:0.00028899645979336774|epoch:5|change:3512892729822.651|value:21727990.83088348
temp:0.0002881636769685183|epoch:0|change:754233008891.3451|value:21727990.83088348
temp:0.0002881636769685183|epoch:5|change:9087056863545.275|value:21727990.83088348
temp:0.0002873356799080528|epoch:0|change:1489153156703.7727|value:21727990.83088348
temp:0.0002873356799080528|epoch:5|change:3407459532896.785|value:21727990.83088348
temp:0.000286512427476542|epoch:0|change:28927206300295.31|value:21727990.83088348
temp:0.000286512427476542|epoch:5|change:10416750497704.078|value:21727990.83088348
temp:0.0002856938790086424|epoch:0|change:221685742330429.22|value:21727990.83088348
temp:0.0002856938790086424|epoch:5|change:1408367836459.2202|value:21727990.83088348
temp:0.00028487999430240027|epoch:0|change:3407459532896.785|value:21727990.83088348
temp:0.00028487999430240027|epoch:5|change:1741443667656.694|value:21727990.83088348
temp:0.0002840707336126697|epoch:0|change:17996671103833.582|value:2172

temp:0.0002531485349028542|epoch:5|change:135585374950.00581|value:21727990.83088348
temp:0.0002525093112808534|epoch:0|change:11082936412563.53|value:21727990.83088348
temp:0.0002525093112808534|epoch:5|change:411109286054306.94|value:21727990.83088348
temp:0.00025187330772621366|epoch:0|change:1267040859126.0322|value:21727990.83088348
temp:0.00025187330772621366|epoch:5|change:524598956232.0108|value:21727990.83088348
temp:0.00025124049996859486|epoch:0|change:27071863117288.918|value:21727990.83088348
temp:0.00025124049996859486|epoch:5|change:20087315779037.848|value:21727990.83088348
temp:0.0002506108639809535|epoch:0|change:11262686267711.578|value:21727990.83088348
temp:0.0002506108639809535|epoch:5|change:322088971.8660112|value:21727990.83088348
temp:0.0002499843759765014|epoch:0|change:3026710799043.053|value:21727990.83088348
temp:0.0002499843759765014|epoch:5|change:4569748998746.116|value:21727990.83088348
temp:0.00024936101240571033|epoch:0|change:19887440077.380363|valu

temp:0.00022521254433871966|epoch:5|change:823547197798937.8|value:4546043.544941779
temp:0.00022470647716420425|epoch:0|change:44835926257642.22|value:4546043.544941779
temp:0.00022470647716420425|epoch:5|change:33541174424280.336|value:4546043.544941779
temp:0.00022420267922201672|epoch:0|change:33625465290553.9|value:4546043.544941779
temp:0.00022420267922201672|epoch:5|change:11430574052770.469|value:4546043.544941779
temp:0.0002237011352832616|epoch:0|change:154577492708164.94|value:4546043.544941779
temp:0.0002237011352832616|epoch:5|change:60796907451245.49|value:4546043.544941779
temp:0.0002232018302550081|epoch:0|change:950374291750901.0|value:4546043.544941779
temp:0.0002232018302550081|epoch:5|change:38370648791668.734|value:4546043.544941779
temp:0.00022270474917877623|epoch:0|change:104856722494152.52|value:4546043.544941779
temp:0.00022270474917877623|epoch:5|change:487150333341982.06|value:4546043.544941779
temp:0.0002222098772290428|epoch:0|change:8254252466283.672|valu

temp:0.00020241890592581334|epoch:0|change:37195934493331.44|value:4546043.544941779
temp:0.00020241890592581334|epoch:5|change:2230052421977.2812|value:4546043.544941779
temp:0.00020200999949497489|epoch:0|change:32529226094334.465|value:4546043.544941779
temp:0.00020200999949497489|epoch:5|change:4210426919575.1875|value:4546043.544941779
temp:0.00020160274179728833|epoch:0|change:81696845727897.02|value:4546043.544941779
temp:0.00020160274179728833|epoch:5|change:5328200077299.6455|value:4546043.544941779
temp:0.0002011971228811427|epoch:0|change:67612742741.22255|value:4546043.544941779
temp:0.0002011971228811427|epoch:5|change:68360399160089.2|value:4546043.544941779
temp:0.0002007931328748556|epoch:0|change:36477429065559.53|value:4546043.544941779
temp:0.0002007931328748556|epoch:5|change:60720757504775.79|value:4546043.544941779
temp:0.00020039076198587235|epoch:0|change:7364450733562.709|value:4546043.544941779
temp:0.00020039076198587235|epoch:5|change:2635106162746.4175|valu

In [5]:
cel1
 [[ 3.18594595 -1.59297297]
 [ 0.          2.75911013]]
cel2
 [[ 2.46723126e+00 -1.23361563e+00]
 [-1.75506857e-20  2.13668495e+00]]

=====================


 _____
 tA:
 [[12  6]
 [15  6]]
det: -17.99999999999999

 _____
 tB:
 [[15.49564972  7.74782486]
 [19.36956215  7.74782486]]

 _____
 zero:
 [[ 0.00000000e+00 -3.55271368e-15]
 [-7.10542736e-15  0.00000000e+00]]

=====================


 _____
 t_cel2_no_strain:
 [[15.94514737  7.50359876]
 [19.69694675  7.50359876]]

 _____
 Strain diagonal :
 [[1.28864667 0.        ]
 [0.         1.28946272]]

=====================


 _____
 Strain:
 [[ 1.29068483 -0.25813697]
 [ 0.25813697  0.7744109 ]]

 _____
 tB_strained:
 [[15.  8.]
 [19.  8.]]

 _____
 Zero:
 [[ 1.22288249 -1.15026007]
 [ 0.9117953  -0.99471647]]

=====================


 _____
 Super cell:
 [[38.2313514  -2.56101493]
 [47.78918924 -7.33993386]]
det: -158.22676323629145

IndentationError: unexpected indent (1162251243.py, line 2)

In [ ]:
# custom 

a1 = [1,0]; a2=[0,1]
A  = np.transpose([a1,a2])

theta =  np.pi/4
R = [ [ np.cos(theta), -np.sin(theta)], [ np.sin(theta),  np.cos(theta)] ]

b1 = np.sqrt(2)*np.dot(R,a1);  b2 = a2#np.sqrt(2)*np.dot(R,a2) #a2
#b1 = [np.sqrt(2),0]; b2=[0,np.sqrt(2)]
B  = np.transpose([b1,b2])


cel1 = np.array(A)
cel2 = np.array(B)

tA, tB, t_cel2_no_strain, diagonal_strain, strain = super_cell(cel1, cel2, 10, model_par)

zero = np.dot(tA,cel1)-np.dot(np.dot(strain,tB),cel2)
s_cell= np.dot(tA,cel1)


print("\ncel1\n",cel1)
print("cel2\n",cel2)
print("\n=====================\n")
print("\n _____\n tA:\n",tA)
print("det:",det(tA))
print("\n _____\n tB:\n",tB)
print("\n _____\n zero:\n",np.dot(tA,cel1)-np.dot(tB,cel2))
print("\n=====================\n")
print("\n _____\n t_cel2_no_strain:\n",t_cel2_no_strain)
print("\n _____\n Strain diagonal :\n",diagonal_strain)
print("\n=====================\n")
print("\n _____\n Strain:\n", strain)
print("\n _____\n tB_strained:\n", np.dot(strain,tB))
print("\n _____\n Zero:\n", zero)
print("\n=====================\n")
print("\n _____\n Super cell:\n",s_cell)
print("det:",det(s_cell))