In [1]:
import numpy as np 

In [30]:
A= np.array([[11,12],
    [21,22]])
B= np.array([[11,12],
    [21,22]])

mod_a1= np.sqrt(A[0][0]*A[0][0]+A[1][0]*A[1][0])
mod_a2= np.sqrt(A[0][1]*A[0][1]+A[1][1]*A[1][1])

mod_b1= np.sqrt(B[0][0]*B[0][0]+B[1][0]*B[1][0])
mod_b2= np.sqrt(B[0][1]*B[0][1]+B[1][1]*B[1][1])

In [32]:
A[:,1]

array([12, 22])

In [6]:
def cmmmc(x,y):
    a=x
    b=y
    while x!=y:
        if x>y:
            x=x-y
        else:
            y=y-x
    return a*b/x

In [23]:
def angle(v1, v2):
    dot_p = np.dot(v1,v2)
    n1= np.sqrt(np.linalg.norm(v1)*np.linalg.norm(v1))
    n2= np.sqrt(np.linalg.norm(v2)*np.linalg.norm(v2))
    n=n1*n2
    return np.arccos(dot_p/n)

In [33]:
def z_rotation(theta):
    R = np.array([ [ np.cos(theta), -np.sin(theta)], 
          [ np.sin(theta),  np.cos(theta)] ])
    return R

In [24]:
v1 =np.array([0, 1])
v2 =np.array([1, 1])
a=angle(v1, v2)
print(a*(180/np.pi))

45.00000000000001


In [40]:
1/np.sqrt(2)

0.7071067811865475

In [38]:
ang_b1a1=angle(A[:,0],B[:,0])
rot = z_rotation(ang_b1a1)


[[0.7071067811865477, -0.7071067811865474], [0.7071067811865474, 0.7071067811865477]]


In [35]:

a1 = [1,0]; a2=[0,1];
A  = np.transpose([a1,a2]);

theta =  np.pi/4;
R = [ [ np.cos(theta), -np.sin(theta)], [ np.sin(theta),  np.cos(theta)] ];

b1 = np.sqrt(2)*np.dot(R,a1);  b2 = np.sqrt(2)*np.dot(R,a2);
B  = np.transpose([b1,b2]);

print("A:\n",A)
print("B:\n",B)

A:
 [[1 0]
 [0 1]]
B:
 [[ 1. -1.]
 [ 1.  1.]]
