In [1]:
import numpy as np
from numpy.linalg import det ,inv
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator
from genetic_one import Gen1

import random
random.seed(99)

In [2]:
a1 = [1,0]; a2=[0,1];
A  = np.transpose([a1,a2]);

theta =  np.pi/4;
R = [ [ np.cos(theta), -np.sin(theta)], [ np.sin(theta),  np.cos(theta)] ];

b1 = np.sqrt(2)*np.dot(R,a1);  b2 = a2 #np.sqrt(2)*np.dot(R,a2);
B  = np.transpose([b1,b2]);

a = A#np.array([[0,1],[1,0]])
b = B#np.array([[0,5],[5,0]])

In [3]:

eps = 0.0001

bond=20

def tAtB(params):
    tA = np.array([[params[0],params[1]],
                   [params[2],params[3]]])
    
    tB = np.dot(np.dot(tA,a), inv(b)) # tAa=tBb
    
    return tA, tB
          
def fit_fucntion(params):
          
        tA, tB= tAtB(params)
        tAa= np.dot(tA,a)
        tBb= np.dot(tB,b)
        
        # main condition
        zero_mat= tAa - tBb
        s=0
        for row in zero_mat:
            for e in row:
                s+=e*e
        
        # mimimum TA
        detTAa= det(tAa)*det(tAa) # minimum but biger than 0
        detTBb= det(tBb)*det(tBb)
        
        # TB integer 
        cons =9999999
        tB_con = 0  
        for row in tB:
            for e in row:
                tB_con += ((round(e)-e))*((round(e)-e)) # e*e
        tB_con = tB_con*cons
        
        
        f =  1/detTAa + tB_con**2 # s + (2-detTAa)*(2-detTAa)*10 + 1/detTAa + tB_con+1/detTBb # since we are working with integer the smallest pos det is 1
        
        return f

In [4]:
# Experiment settings

#Hyperparameters of the model
model_par = {
    
    'cell_split_number': 4, 
    'subjects_in_cell': 3,

    'nr_clones': 10,
    'mutation_gaussian_sd': 4,

    'pins': 7,
    'gene_quality': 1,
    
}




input_size = 4 # P=[tA00,tA01,tA10,tA11]

bounds =[[-bond,bond]for _ in range(input_size)] # searching intervals for the solution

# Experiment
experiment = Gen1(fit_fucntion ,input_size, bounds, model_par)

In [5]:
## Automate evolution

nr_epochs = 100
last_generation = experiment.evolve(nr_epochs)
fit = [fit_fucntion(x) for x in last_generation] 
print("fit:",fit)


Epochs 0/100


/var/folders/3_/hxxz6cjj6k92q_tqrvht1tf80000gn/T/ipykernel_92046/1288950215.py:39: RuntimeWarning: divide by zero encountered in double_scalars
  f =  1/detTAa + tB_con**2 # s + (2-detTAa)*(2-detTAa)*10 + 1/detTAa + tB_con+1/detTBb # since we are working with integer the smallest pos det is 1


perf [-2.712673611111111e-05, -6.200012400024802e-05, -1.4457343607685542e-05, -1.9578667084344884e-05, -5.004779564484078e-06, -7.304601899196499e-06, -4.938271604938279e-06, -1.0892178326743553e-05, -1.0405827263267427e-05, -6.409229290177854e-06, -4.0647762747138435e-06, -4.268834096031687e-06, -1.2755102040816335e-05, -1.3417595835178253e-05, -2.6030820491461865e-05, -9.018027036045055e-06, -6.298815822625347e-05, -4.216562658121096e-05, -9.644689633887578e-06, -8.210113217461272e-06, -1.8579072532699173e-05, -8.45051379123851e-06, -7.673360394717666e-06, -1.0405827263267427e-05, -1.1569253551760844e-05, -1.0405827263267427e-05, -7.89041787653074e-06, -2.2041482069254318e-05, -1.082063711911357e-05, -2.402921953094965e-05, -6.103515625000003e-05, -4.6277014207043376e-05, -3.1561671506122976e-05, -1.479289940828403e-05, -7.979826997350688e-06, -1.1809024456489664e-05, -2.8246592754748937e-06, -4.664853593569966e-06, -4.395044148218474e-06, -4.2865287261722625e-06, -1.074979844127922

perf [-1.3717421124828549e-05, -8.650519031141862e-06, -0.0001876524676299494, -2.921840759678595e-05, -6.103515625000003e-05, -2.859675712774175e-05, -1.3819598955238318e-05, -1.1413440467494525e-05, -4.385772553835358e-05, -2.402921953094965e-05, -3.955539733396622e-05, -2.4507401235173048e-05, -2.7411529289219047e-05, -3.342145456854573e-06, -0.00010412328196584746, -2.0290560831101378e-05, -4.6277014207043376e-05, -7.305135510263712e-05, -1.0339016345984847e-05, -2.1633315305570554e-05, -9.409462155143212e-06, -1.5378700499807778e-05, -1.479289940828403e-05, -1.2140489747356424e-05, -1.3922922699933176e-05, -1.2056327160493847e-05, -9.018027036045055e-06, -1.0892178326743553e-05]
Epochs 3/100
perf [-5.141890467449262e-06, -1.239833366395558e-05, -8.910670527957232e-06, -8.701629815264405e-06, -2.525188757859651e-05, -7.226268932824598e-06, -1.1336711673412006e-05, -9.70487475859124e-06, -9.585062638384346e-06, -7.9798269973507e-06, -2.379535990481855e-05, -2.6570305027101702e-05, -

perf [-2.029204308406589e-06, -1.8212249194563292e-06, -2.029204308406589e-06, -2.137409801306386e-06, -1.918340098679416e-06, -2.137409801306386e-06, -2.0176911157024802e-06, -2.254506759011263e-06, -2.1311737439394732e-06, -2.137409801306382e-06, -2.137409801306382e-06, -2.137409801306382e-06, -2.254506759011263e-06, -2.137409801306386e-06, -2.1626297577854648e-06, -2.254506759011263e-06, -2.254506759011263e-06, -2.1311737439394732e-06, -2.254506759011263e-06, -2.149964310592447e-06, -2.254506759011263e-06, -2.254506759011263e-06, -2.254506759011263e-06, -2.2477516863757004e-06, -2.006275630171176e-06, -2.254506759011263e-06, -2.1311737439394732e-06, -2.1249649380785196e-06]
Epochs 15/100
perf [-1.9290123456790115e-06, -2.1249649380785196e-06, -2.137409801306382e-06, -2.029204308406589e-06, -2.029204308406589e-06, -2.029204308406589e-06, -2.0234354291403064e-06, -2.1249649380785196e-06, -1.7313019390581742e-06, -2.0176911157024802e-06, -2.0176911157024802e-06, -2.0176911157024802e-06

perf [-1.8261504747991247e-06, -1.8212249194563292e-06, -1.8163192653351836e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8163192653351836e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.7313019390581742e-06, -1.8163192653351836e-06, -1.8163192653351836e-06, -1.8163192653351836e-06, -1.8163192653351836e-06, -1.8212249194563292e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8212249194563292e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8261504747991247e-06]
Epochs 28/100
perf [-1.8163192653351836e-06, -1.7313019390581742e-06, -1.8163192653351836e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8261504747991247e-06, -1.8261504747991247e-06,

perf [-1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06]
Epochs 40/100
perf [-1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06,

perf [-1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06]
Epochs 53/100
perf [-1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06,

perf [-1.7313019390581742e-06, -1.6436554898093354e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06]
Epochs 66/100
perf [-1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06,

perf [-1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7267548577931027e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06]
Epochs 79/100
perf [-1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06,

perf [-1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06]
Epochs 91/100
perf [-1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06, -1.7313019390581742e-06,

In [6]:
best =last_generation [fit.index(min(fit))]
print(best)

[-20, -20, -20, 20]


In [7]:
P = best #[1, 1, 0, 1]#[2, 0, 0, -1]#[0, -1, -1, 0]#[-1, 1, 0, 1]
tA,tB = tAtB(P)
zero_mat= np.dot(tA,a) - np.dot(tB,b)
print("\n _____\n tA:\n",tA)
print("det:",det(tA))
print("\n _____\n tB:\n",tB)
print("det:",det(tB))
print("\n zero_mat:\n",zero_mat)


 _____
 tA:
 [[-20 -20]
 [-20  20]]
det: -799.9999999999999

 _____
 tB:
 [[  0. -20.]
 [-40.  20.]]
det: -799.9999999999999

 zero_mat:
 [[0. 0.]
 [0. 0.]]
