In [15]:
import numpy as np

import matplotlib
import matplotlib.pyplot as plt



from vdw_evolve import allign_along_10

ModuleNotFoundError: No module named 'vdw_evolve'

In [20]:
cell1 = np.array([[2.467, 2.467 / 2], [0, 2.467 * np.sqrt(3) / 2]])
cell2 = np.array([[5.75, 0], [0, 5.92]])

cell1 = allign_along_10([graphene_cell, pbse_cell])
cell2 = aligned_cells[0]
pbse_cell = aligned_cells[1]

NameError: name 'allign_along_10' is not defined

In [4]:
import math

def find_xy(c):
    prime_factors = []
    i = 2
    while i * i <= c:
        if c % i == 0:
            count = 0
            while c % i == 0:
                count += 1
                c //= i
            prime_factors.append((i, count))
        i += 1
    if c > 1:
        prime_factors.append((c, 1))

    x = 1
    y = 1
    for p, a in prime_factors:
        if a % 2 == 0:
            x *= p**(a//2)
            y *= p**(a//2)
        else:
            x *= p**(a//2)
            y *= p**(a//2 + 1)
    return (x, y)

c = float(input("Enter the value of constant c: "))
x, y = find_xy(c)
print("x:", x)
print("y:", y)

Enter the value of constant c: 5
x: 1.0
y: 5.0


In [8]:
def find_integer_multiple(c):
    x = int(math.ceil(c))
    print(x)
    while True:
        z = x * c
        if z == int(z):
            return z/c
        x -= 1

c = float(input("Enter a real number c: "))
result = find_integer_multiple(c)
if result is not None:
    print("The integer x that gives an integer result when multiplied with", c, "is", result)
else:
    print("No solution exists.")

Enter a real number c: 3.2
4
The integer x that gives an integer result when multiplied with 3.2 is 0.0


In [16]:
import numpy as np

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def lcm(a, b):
    return a * b // gcd(a, b)

def find_minimal_supercell(cell1, cell2):
    a1, a2 = np.array(cell1)
    b1, b2 = np.array(cell2)
    l1 = lcm(np.linalg.norm(a1, ord=1), np.linalg.norm(a2, ord=1))
    l2 = lcm(np.linalg.norm(b1, ord=1), np.linalg.norm(b2, ord=1))
    l = lcm(l1, l2)
    supercell = [a1 * l // l1, a2 * l // l1, b1 * l // l2, b2 * l // l2]
    return supercell

cell_1 = [[1, 0], [0, 2]]
cell_2 = [[2, 0], [0, 1]]
result = find_minimal_supercell(cell1, cell2)
print("The minimal super cell is:\n", result)

The minimal super cell is:
 [array([4.72746681e+16, 2.36373340e+16]), array([0.00000000e+00, 4.09410635e+16]), array([5.11832451e+16, 0.00000000e+00]), array([0.00000000e+00, 5.26964889e+16])]


In [17]:
cell_1 = [np.array(cell1[0]).T, np.array(cell1[1]).T]
cell_2 = [np.array(cell2[0]).T, np.array(cell2[1]).T]
result = find_minimal_supercell(cell1, cell2)
print("The minimal super cell is:\n", result)

The minimal super cell is:
 [array([4.72746681e+16, 2.36373340e+16]), array([0.00000000e+00, 4.09410635e+16]), array([5.11832451e+16, 0.00000000e+00]), array([0.00000000e+00, 5.26964889e+16])]


In [18]:
import numpy as np

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def lcm(a, b):
    return a * b // gcd(a, b)

def find_minimal_supercell(cell1, cell2, a_range):
    a1, a2 = np.array(cell1)
    b1, b2 = np.array(cell2)
    l1 = lcm(np.linalg.norm(a1, ord=1), np.linalg.norm(a2, ord=1))
    min_l2 = float("inf")
    min_Tb = None
    for a in a_range:
        strain = [[1 + a, 0], [0, 1 - a]]
        b1 = np.dot(strain, b1)
        b2 = np.dot(strain, b2)
        l2 = lcm(np.linalg.norm(b1, ord=1), np.linalg.norm(b2, ord=1))
        if l2 < min_l2:
            min_l2 = l2
            min_Tb = np.array([b1 * l2 // np.linalg.norm(b1, ord=1), b2 * l2 // np.linalg.norm(b2, ord=1)])
    l = lcm(l1, min_l2)
    Ta = np.array([a1 * l // l1, a2 * l // l1])
    Tb = min_Tb
    return Ta, Tb

cell1 = [[1, 0], [0, 2]]
cell2 = [[2, 0], [0, 1]]
a_range = np.linspace(-0.5, 0.5, 101)
Ta, Tb = find_minimal_supercell(cell1, cell2, a_range)
print("The matrices Ta and Tb are:")
print(Ta)
print(Tb)


The matrices Ta and Tb are:
[[3. 0.]
 [0. 6.]]
[[3. 0.]
 [0. 3.]]


In [21]:
cell1 = np.array([[2.467, 2.467 / 2], [0, 2.467 * np.sqrt(3) / 2]])
cell2 = np.array([[5.75, 0], [0, 5.92]])

cell_1 = [np.array(cell1[0]).T, np.array(cell1[1]).T]
cell_2 = [np.array(cell2[0]).T, np.array(cell2[1]).T]
a_range = np.linspace(-0.5, 0.5, 101)
Ta, Tb = find_minimal_supercell(cell_1, cell_2, a_range)
print("The matrices Ta and Tb are:")
print(Ta)
print(Tb)



The matrices Ta and Tb are:
[[4.86847303e+14 2.43423651e+14]
 [0.00000000e+00 4.21622132e+14]]
[[1.9734386e+14 0.0000000e+00]
 [0.0000000e+00 1.9734386e+14]]
