In [1]:
import numpy as np
from numpy.linalg import det
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator
from genetic_one import Gen1

In [2]:
a = np.array([[0,1],[1,0]])
b = np.array([[0,5],[5,0]])
eps = 0.0001

bond=10

def tAtB(params):
#     print("params", params)
    tA = np.array([[params[0],0],
                   [0, params[1]]])
    tB = np.array([[params[2],0],
                   [0, params[3]]])
    return tA, tB
          
def fit_fucntion(params):
          
        tA, tB= tAtB(params)
        tAa= np.dot(tA,a)
        tBa= np.dot(tB,b)
        
        zero_mat= tAa - tBa
        
        s=0
        for row in zero_mat:
            for e in row:
                s+=e*e
        
        detTAa= det(tAa)*det(tAa) # minimum but biger than 0
        detTBa= det(tBa)*det(tBa)
        
        f = s*1000 + 1/detTAa + 1/detTBa #+(1-detTAa)*(1-detTAa)*10
        return f 

In [3]:
# Experiment settings

#Hyperparameters of the model
model_par = {
    
    'cell_split_number': 2, 
    'subjects_in_cell': 5,

    'nr_clones': 10,
    'mutation_gaussian_sd': 4,

    'pins': 7,
    'gene_quality': 1,
    
}




input_size = 4 # P=[tA00,tA01,tA10,tA11,tB00,tB01,tB10,tB11]

bounds =[[-bond,bond]for _ in range(input_size)] # searching intervals for the solution

# Experiment
experiment = Gen1(fit_fucntion ,input_size, bounds, model_par)

In [4]:
## Automate evolution

nr_epochs = 30
last_generation = experiment.evolve(nr_epochs)
fit = [fit_fucntion(x) for x in last_generation] 
print("fit:",fit)


Epochs 0/30
perf [-404000.00450844446, -109000.0116, -353000.0026675737, -13000.000816493128, -4000.0024163265307, -820000.0069604445, -229000.00121632652, -292000.012409679, -1508000.0039078125, -281000.000725, -882000.0003478738, -317000.0123567901, -340000.00066689344, -1325000.0016444444, -82000.00094938272, -1205000.015632111, -173000.0023675737, -676000.0006716049, -225000.2501, -1060000.0069484445, -1850000.0031114197, -181000.0041, -10000.0025765625, -369000.00063125, -481000.00050982716, -218000.0039260031, -185000.00059189342, -317001.00004444446, -202000.012370679, -361000.0002937778, -1421000.0100071111, -1097000.001752111, -1810000.2500027777, -80000.00348641975, -712000.0003540467, -1361000.000496605, -697000.0007778549, -677000.0278417778, -965000.0004500278, -580000.0069555556, -410000.0004980278, -680000.0004590277, -13000.000644140626, -232000.0017611111, -793000.0051270408, -712000.0278777777, -605000.0156361111, -5000.000834027777, -925000.0069555556, -740000.000578

/var/folders/3_/hxxz6cjj6k92q_tqrvht1tf80000gn/T/ipykernel_46662/2858485200.py:31: RuntimeWarning: divide by zero encountered in double_scalars
  f = s*1000 + 1/detTAa + 1/detTBa #+(1-detTAa)*(1-detTAa)*10


perf [-450000.0010405625, -36000.0029, -101000.00267777778, -16000.0416, -265000.0009876736, -164000.0104, -41000.0404, -185000.0007446712, -52001.0016, -130000.2504, -85000.2516, -40000.11271111111, -85000.2516, -36000.00067160494, -72001.0016, -13000.000644140626, -288000.01236543205, -245000.25017777778, -18000.00550625, -34000.0104, -34000.0104, -2000.0033361111111, -178000.00520204083, -290000.00128662126, -73000.02937777778, -197000.00087160495, -53000.01274567901, -305000.00696944445]
Epochs 2/30
perf [-101000.00267777778, -100000.015725, -193000.02795555556, -164000.0009941043, -137000.00178055555, -137000.00178055555, -29000.004844444444, -170000.00854444443, -32000.02817777778, -185000.017225, -58000.0641, -234000.0041, -389000.0101777778, -53000.01274567901, -65000.00468641976, -113000.02937777778, -706000.0006576531, -185000.1115111111, -80000.2504, -68000.02817777779, -68000.02817777779, -68000.02817777779, -20000.000592901237, -450000.0010405625, -450000.0010405625, -6100

perf [-1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.001025]
Epochs 18/30
perf [-1000.0027111111111, -5000.0013765625, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.001025, -5000.0013765625, -5000.0013765625, -4000.0024163265307, -5000.0013765625, -5000.0013765625, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.0027111111111, -1000.00271111111

In [5]:
best =last_generation [fit.index(min(fit))]
print(best)

[-5, -6, -1, -1]


In [6]:
P= best#[2, 1, -8, -3, 1, 0, 0, -1]
tA,tB = tAtB(P)
zero_mat= np.dot(tA,a) - np.dot(tB,b)
print("\n _____\n tA:\n",tA)
print("\n _____\n tB:\n",tB)

print("\n zero_mat:\n",zero_mat)


 _____
 tA:
 [[-5  0]
 [ 0 -6]]

 _____
 tB:
 [[-1  0]
 [ 0 -1]]

 zero_mat:
 [[ 0  0]
 [-1  0]]
