In [1]:
import numpy as np
from numpy.linalg import det ,inv
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator
from genetic_one import Gen1

In [2]:
a = np.array([[0,1],[1,0]])
b = np.array([[0,5],[5,0]])
eps = 0.0001

bond=10

def tAtB(params):
    tA = np.array([[params[0],params[1]],
                   [params[2],params[3]]])
    
    tB = np.dot(np.dot(tA,a), inv(b)) # tAa=tBb
    
    return tA, tB
          
def fit_fucntion(params):
          
        tA, tB= tAtB(params)
        tAa= np.dot(tA,a)
        
        # main condition
        zero_mat= tAa - np.dot(tB,b)
        s=0
        for row in zero_mat:
            for e in row:
                s+=e*e
        
        # mimimum TA
        detTAa= det(tAa)*det(tAa) # minimum but biger than 0
        
        # TB integer 
        cons =1000
        tB_con = 0  
        for row in tB:
            for e in row:
                tB_con += (int(e)-e)*(int(e)-e) # e*e
        tB_con = tB_con*cons
        
        
        f = s + 1/detTAa + tB_con  # since we are working with integer the smallest pos det is 1
        
        return f

In [3]:
# Experiment settings

#Hyperparameters of the model
model_par = {
    
    'cell_split_number': 2, 
    'subjects_in_cell': 3,

    'nr_clones': 10,
    'mutation_gaussian_sd': 4,

    'pins': 7,
    'gene_quality': 1,
    
}




input_size = 4 # P=[tA00,tA01,tA10,tA11]

bounds =[[-bond,bond]for _ in range(input_size)] # searching intervals for the solution

# Experiment
experiment = Gen1(fit_fucntion ,input_size, bounds, model_par)

In [7]:
## Automate evolution

nr_epochs = 20
last_generation = experiment.evolve(nr_epochs)
fit = [fit_fucntion(x) for x in last_generation] 
print("fit:",fit)


Epochs 0/20
Evolution process ended!
Last generation: [[3, 0, -10, -5], [5, 3, -4, -2], [4, 0, -4, 0], [-1, -2, -5, 2], [-1, -2, -5, 2], [-1, -2, -5, 2], [-1, -2, -5, 2], [7, 6, 1, 2], [6, 2, 1, 4], [1, 0, 0, 5], [1, 0, 0, 5], [1, 0, 0, 5], [1, 0, 0, 5], [5, -1, 1, 6], [0, -3, 0, 7], [0, -3, 0, 7], [0, -3, 0, 7], [0, -3, 0, 7], [-5, -5, 0, 8], [-5, -5, 0, 8], [-5, -5, 0, 8], [-5, -5, 0, 8], [-5, -5, 0, 8], [-5, -5, 0, 8], [-5, -5, 0, 8], [-5, -5, 0, 8], [-5, -5, 0, 8], [-5, -5, 0, 8]]
Epochs 1/20


/var/folders/3_/hxxz6cjj6k92q_tqrvht1tf80000gn/T/ipykernel_41749/2420828598.py:39: RuntimeWarning: divide by zero encountered in double_scalars
  f = s + 1/detTAa + tB_con  # since we are working with integer the smallest pos det is 1


Evolution process ended!
Last generation: [[1, 0, 0, 5], [-2, -5, 2, 2], [-2, 0, -2, 6], [0, 0, -1, 2], [2, 0, -5, 0], [2, 0, -5, 0], [2, 0, -5, 0], [-5, -10, 5, 0], [-5, -5, 0, 4], [-3, -6, 2, 0], [-1, -5, -2, -2], [-1, -5, -2, -2], [-1, -5, -2, -2], [-5, 0, -5, 7], [-3, 0, -4, 4], [-1, 0, -8, 1], [-1, 0, -8, 1], [-1, 0, -8, 1], [-1, -1, -2, 0], [1, 0, -6, -2], [1, 0, -6, -2], [1, 0, -6, -2], [3, 0, -10, -5], [3, 0, -10, -5], [3, 0, -10, -5], [3, 0, -10, -5], [3, 0, -10, -5], [3, 0, -10, -5]]
Epochs 2/20
Evolution process ended!
Last generation: [[-1, -1, 5, 6], [2, 2, -2, -2], [2, -1, -2, 3], [-1, -3, 2, 2], [0, 0, 2, 6], [0, 0, 2, 6], [0, 0, 2, 6], [5, 6, -10, -10], [5, 2, -10, -5], [2, 0, -6, -6], [3, 3, -5, -2], [3, 3, -5, -2], [3, 3, -5, -2], [5, -1, -10, 0], [2, -3, -6, -1], [3, 0, -5, 2], [3, 0, -5, 2], [3, 0, -5, 2], [-1, -5, -2, -2], [0, -2, -1, 2], [0, -2, -1, 2], [0, -2, -1, 2], [1, 0, 0, 5], [1, 0, 0, 5], [1, 0, 0, 5], [1, 0, 0, 5], [1, 0, 0, 5], [1, 0, 0, 5]]
Epochs 3/20


Evolution process ended!
Last generation: [[-1, -10, 10, 0], [0, -4, 8, -2], [2, -6, 6, 0], [4, -6, 8, 0], [2, -10, 8, 0], [2, -10, 8, 0], [2, -10, 8, 0], [1, 2, 5, -5], [3, 0, 3, -2], [6, 0, 5, -2], [3, -4, 5, -2], [3, -4, 5, -2], [3, -4, 5, -2], [5, -2, 1, 0], [8, -2, 3, 0], [5, -6, 3, 0], [5, -6, 3, 0], [5, -6, 3, 0], [10, -1, 5, 1], [8, -6, 5, 0], [8, -6, 5, 0], [8, -6, 5, 0], [5, -10, 5, 0], [5, -10, 5, 0], [5, -10, 5, 0], [5, -10, 5, 0], [5, -10, 5, 0], [5, -10, 5, 0]]
Epochs 19/20
Evolution process ended!
Last generation: [[8, -6, 5, 0], [6, -8, 5, 0], [9, -4, 5, 0], [4, -8, 8, 0], [4, -8, 8, 0], [4, -8, 8, 0], [4, -8, 8, 0], [5, -10, 5, 0], [8, -6, 5, 0], [2, -10, 8, 0], [2, -10, 8, 0], [2, -10, 8, 0], [2, -10, 8, 0], [10, -1, 5, 1], [4, -6, 8, 0], [4, -6, 8, 0], [4, -6, 8, 0], [4, -6, 8, 0], [-1, -10, 10, 0], [-1, -10, 10, 0], [-1, -10, 10, 0], [-1, -10, 10, 0], [-1, -10, 10, 0], [-1, -10, 10, 0], [-1, -10, 10, 0], [-1, -10, 10, 0], [-1, -10, 10, 0], [-1, -10, 10, 0]]
fit: [40

In [12]:
best =last_generation [fit.index(min(fit))]
print(best)

[5, -10, 5, 0]


In [13]:
P=  best #[1, 1, 0, 1]#[2, 0, 0, -1]#[0, -1, -1, 0]#[-1, 1, 0, 1]
tA,tB = tAtB(P)
zero_mat= np.dot(tA,a) - np.dot(tB,b)
print("\n _____\n tA:\n",tA)
print("\n _____\n tB:\n",tB)

print("\n zero_mat:\n",zero_mat)


 _____
 tA:
 [[  5 -10]
 [  5   0]]

 _____
 tB:
 [[ 1. -2.]
 [ 1.  0.]]

 zero_mat:
 [[0. 0.]
 [0. 0.]]
